Fix umount code insertion position
dabao1955/kernel_build_action pull request #61
Opened 2024-12-18 06:23 UTC by Fyg369

## Title

## Description

## Type
- [ ] bug fix 

- [ ] feature add 

- [ ] other 

## Checkbox
- [ ] do not have break changes 

- [ ] normal operation will not be affected after modification 

## Linked issues
<!-- if want to fix it, try "fixes: #13">

2024-12-18 13:21 UTC, dabao1955 requested changes

2024-12-18 13:21 UTC, dabao1955 commented on kernelsu/patch.sh
> +        sed -i '/may_mandlock(void)/,/^}/ { /^}/a \
使用grep检测到没有这个函数然后sed可能会更好一些

2024-12-18 14:13 UTC, Fyg369 commented on kernelsu/patch.sh
> +        sed -i '/may_mandlock(void)/,/^}/ { /^}/a \
> 使用grep检测到没有这个函数然后sed可能会更好一些

这样修改？
fs/namespace.c)
    can_umount_code='#ifdef CONFIG_KSU
static int can_umount(const struct path *path, int flags)
{
    struct mount *mnt = real_mount(path->mnt);

    if (flags & ~(MNT_FORCE | MNT_DETACH | MNT_EXPIRE | UMOUNT_NOFOLLOW))
        return -EINVAL;
    if (!may_mount())
        return -EPERM;
    if (path->dentry != path->mnt->mnt_root)
        return -EINVAL;
    if (!check_mnt(mnt))
        return -EINVAL;
    if (mnt->mnt.mnt_flags & MNT_LOCKED) /* Check optimistically */
        return -EINVAL;
    if (flags & MNT_FORCE && !capable(CAP_SYS_ADMIN))
        return -EPERM;
    return 0;
}

int path_umount(struct path *path, int flags)
{
    struct mount *mnt = real_mount(path->mnt);
    int ret;

    ret = can_umount(path, flags);
    if (!ret)
        ret = do_umount(mnt, flags);

    /* we must not call path_put() as that would clear mnt_expiry_mark */
    dput(path->dentry);
    mntput_no_expire(mnt);
    return ret;
}
#endif'

    if grep -q "may_mandlock(void)" "$i"; then
        sed -i "/may_mandlock(void)/,/^}/ { /^}/a\\$can_umount_code" "$i"
    else
        sed -i "/int ksys_umount(char __user \*name, int flags)/i\\$can_umount_code" "$i"
    fi
    ;;

2024-12-19 07:34 UTC, Fyg369 commented on kernelsu/patch.sh
> +        sed -i '/may_mandlock(void)/,/^}/ { /^}/a \
> 测试过可以就行

经过测试sed命令无法处理这种插入多行代码的变量，大佬有什么好的建议吗？

2024-12-19 10:05 UTC, Fyg369 commented
试了很多方法都不是很理想，但是用sed命令插入显的代码太冗长了

    fs/namespace.c)
        if grep -q "may_mandlock(void)" "$i"; then
            sed -i '/may_mandlock(void)/,/^}/ { /^}/a \
#ifdef CONFIG_KSU\
static int can_umount(const struct path *path, int flags)\
{\
    struct mount *mnt = real_mount(path->mnt);\
\
    if (flags & ~(MNT_FORCE | MNT_DETACH | MNT_EXPIRE | UMOUNT_NOFOLLOW))\
        return -EINVAL;\
    if (!may_mount())\
        return -EPERM;\
    if (path->dentry != path->mnt->mnt_root)\
        return -EINVAL;\
    if (!check_mnt(mnt))\
        return -EINVAL;\
    if (mnt->mnt.mnt_flags & MNT_LOCKED) /* Check optimistically */\
        return -EINVAL;\
    if (flags & MNT_FORCE && !capable(CAP_SYS_ADMIN))\
        return -EPERM;\
    return 0;\
}\
\
int path_umount(struct path *path, int flags)\
{\
    struct mount *mnt = real_mount(path->mnt);\
    int ret;\
\
    ret = can_umount(path, flags);\
    if (!ret)\
        ret = do_umount(mnt, flags);\
\
    /* we must not call path_put() as that would clear mnt_expiry_mark */\
    dput(path->dentry);\
    mntput_no_expire(mnt);\
    return ret;\
}\
#endif
}' fs/namespace.c
        else
            sed -i '/int ksys_umount(char __user \*name, int flags)/i \
#ifdef CONFIG_KSU\
static int can_umount(const struct path *path, int flags)\
{\
    struct mount *mnt = real_mount(path->mnt);\
\
    if (flags & ~(MNT_FORCE | MNT_DETACH | MNT_EXPIRE | UMOUNT_NOFOLLOW))\
        return -EINVAL;\
    if (!may_mount())\
        return -EPERM;\
    if (path->dentry != path->mnt->mnt_root)\
        return -EINVAL;\
    if (!check_mnt(mnt))\
        return -EINVAL;\
    if (mnt->mnt.mnt_flags & MNT_LOCKED) /* Check optimistically */\
        return -EINVAL;\
    if (flags & MNT_FORCE && !capable(CAP_SYS_ADMIN))\
        return -EPERM;\
    return 0;\
}\
\
int path_umount(struct path *path, int flags)\
{\
    struct mount *mnt = real_mount(path->mnt);\
    int ret;\
\
    ret = can_umount(path, flags);\
    if (!ret)\
        ret = do_umount(mnt, flags);\
\
    /* we must not call path_put() as that would clear mnt_expiry_mark */\
    dput(path->dentry);\
    mntput_no_expire(mnt);\
    return ret;\
}\
#endif\
' fs/namespace.c
        fi
        ;;

2024-12-19 13:48 UTC, dabao1955 commented
> 试了很多方法都不是很理想，但是用sed命令插入显的代码太冗长了
> 
>     fs/namespace.c)
>         if grep -q "may_mandlock(void)" "$i"; then
>             sed -i '/may_mandlock(void)/,/^}/ { /^}/a \
> #ifdef CONFIG_KSU\
> static int can_umount(const struct path *path, int flags)\
> {\
>     struct mount *mnt = real_mount(path->mnt);\
> \
>     if (flags & ~(MNT_FORCE | MNT_DETACH | MNT_EXPIRE | UMOUNT_NOFOLLOW))\
>         return -EINVAL;\
>     if (!may_mount())\
>         return -EPERM;\
>     if (path->dentry != path->mnt->mnt_root)\
>         return -EINVAL;\
>     if (!check_mnt(mnt))\
>         return -EINVAL;\
>     if (mnt->mnt.mnt_flags & MNT_LOCKED) /* Check optimistically */\
>         return -EINVAL;\
>     if (flags & MNT_FORCE && !capable(CAP_SYS_ADMIN))\
>         return -EPERM;\
>     return 0;\
> }\
> \
> int path_umount(struct path *path, int flags)\
> {\
>     struct mount *mnt = real_mount(path->mnt);\
>     int ret;\
> \
>     ret = can_umount(path, flags);\
>     if (!ret)\
>         ret = do_umount(mnt, flags);\
> \
>     /* we must not call path_put() as that would clear mnt_expiry_mark */\
>     dput(path->dentry);\
>     mntput_no_expire(mnt);\
>     return ret;\
> }\
> #endif
> }' fs/namespace.c
>         else
>             sed -i '/int ksys_umount(char __user \*name, int flags)/i \
> #ifdef CONFIG_KSU\
> static int can_umount(const struct path *path, int flags)\
> {\
>     struct mount *mnt = real_mount(path->mnt);\
> \
>     if (flags & ~(MNT_FORCE | MNT_DETACH | MNT_EXPIRE | UMOUNT_NOFOLLOW))\
>         return -EINVAL;\
>     if (!may_mount())\
>         return -EPERM;\
>     if (path->dentry != path->mnt->mnt_root)\
>         return -EINVAL;\
>     if (!check_mnt(mnt))\
>         return -EINVAL;\
>     if (mnt->mnt.mnt_flags & MNT_LOCKED) /* Check optimistically */\
>         return -EINVAL;\
>     if (flags & MNT_FORCE && !capable(CAP_SYS_ADMIN))\
>         return -EPERM;\
>     return 0;\
> }\
> \
> int path_umount(struct path *path, int flags)\
> {\
>     struct mount *mnt = real_mount(path->mnt);\
>     int ret;\
> \
>     ret = can_umount(path, flags);\
>     if (!ret)\
>         ret = do_umount(mnt, flags);\
> \
>     /* we must not call path_put() as that would clear mnt_expiry_mark */\
>     dput(path->dentry);\
>     mntput_no_expire(mnt);\
>     return ret;\
> }\
> #endif\
> ' fs/namespace.c
>         fi
>         ;;

那么patch呢

2024-12-20 05:55 UTC, Fyg369 commented
重修修改了一下，在乌班图本地测试正常，已提交修改，看下是否还有其它问题需要修改

2024-12-20 09:37 UTC, Fyg369 commented
已在乌班图本地测试没问题，大佬看下是否还有其它要修改的

2024-12-20 13:20 UTC, dabao1955 commented
> 已在乌班图本地测试没问题，大佬看下是否还有其它要修改的

如果4.4,4.9,4.14,4.19,5.4测试过都没问题就行

2024-12-20 15:54 UTC, dabao1955 commented
> > > 已在乌班图本地测试没问题，大佬看下是否还有其它要修改的
> > 
> > 如果4.4,4.9,4.14,4.19,5.4测试过都没问题就行
> 
> 插入的代码其实没做太大改变，只是添加了判断，根据判断插入相应位置的代码，至于下图的代码是为了适应两个不同位置，执行修改删除补丁脚本花括号而已，因为这两个插入位置有一个花括号不兼容。
> 
> ![6](https://github.com/user-attachments/assets/856234ee-287e-434d-9474-6cb592789788)
> 
> ![9](https://github.com/user-attachments/assets/9f1036ce-27bc-46aa-b8ad-6e7224d1e97e)
> 

ok

2024-12-20 15:54 UTC, dabao1955 approved these changes

2024-12-20 15:54 UTC, merged

2024-12-21 00:43 UTC, Fyg369 commented
分支合并又出现Bug了  

![6](https://github.com/user-attachments/assets/063ec957-895b-45df-ba2a-0f4dd06dc52c)